name: Rust
on:
  push:
    branches: ['main']
    paths:
      - '**/*.rs'
      - 'src/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - '**/*.rs'
      - 'src/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check the formatting
        run: cargo fmt --all --check

      - name: Clip clip
        run: cargo clippy -- -Dwarnings
